// AI 服务商配置表
export const PROVIDERS = {
  deepseek: {
    label: 'DeepSeek',
    emoji: '🔵',
    baseUrl: 'https://api.deepseek.com/v1',
    model: 'deepseek-chat',
    keyHint: 'sk-xxxxxxxxxxxxxxxx',
    keyUrl: 'https://platform.deepseek.com/api_keys',
    topUpUrl: 'https://platform.deepseek.com/top_up',
    officialSite: 'https://platform.deepseek.com',
    guideDesc: '适合国内用户，充值门槛低，中文场景表现较好',
    recommendLevel: '推荐',
    difficulty: '低',
    pricingNote: '按官方平台实际价格为准',
    supportsBalance: true,
  },
  openai: {
    label: 'OpenAI',
    emoji: '🟢',
    baseUrl: 'https://api.openai.com/v1',
    model: 'gpt-4o-mini',
    keyHint: 'sk-xxxxxxxxxxxxxxxx',
    keyUrl: 'https://platform.openai.com/api-keys',
    topUpUrl: 'https://platform.openai.com/settings/organization/billing',
    officialSite: 'https://platform.openai.com',
    guideDesc: '模型生态完整，适合需要通用能力和英文场景的用户',
    recommendLevel: '进阶',
    difficulty: '中',
    pricingNote: '按 OpenAI 官方账单和模型价格为准',
    supportsBalance: false,
  },
  claude: {
    label: 'Claude（Anthropic）',
    emoji: '🟠',
    baseUrl: 'https://api.anthropic.com',
    model: 'claude-haiku-4-5-20251001',
    keyHint: 'sk-ant-xxxxxxxxxxxxxxxx',
    keyUrl: 'https://platform.claude.com/settings/keys',
    topUpUrl: 'https://platform.claude.com/settings/billing',
    officialSite: 'https://platform.claude.com',
    guideDesc: '适合长文本分析、写作和稳健对话场景',
    recommendLevel: '进阶',
    difficulty: '中',
    pricingNote: '按 Anthropic 官方账单和模型价格为准',
    supportsBalance: false,
  },
  kimi: {
    label: 'Kimi（月之暗面）',
    emoji: '🌙',
    baseUrl: 'https://api.moonshot.cn/v1',
    model: 'moonshot-v1-8k',
    keyHint: 'sk-xxxxxxxxxxxxxxxx',
    keyUrl: 'https://platform.kimi.com/console/api-keys',
    // 未找到独立可直达的充值页，暂用官方账户页。
    topUpUrl: 'https://platform.kimi.com/console/account',
    officialSite: 'https://platform.kimi.com',
    guideDesc: '适合中文长文本和国内使用场景，平台入口相对清晰',
    recommendLevel: '可选',
    difficulty: '低',
    pricingNote: '按月之暗面官方平台实际价格为准',
    supportsBalance: false,
  },
} as const;

export type ProviderId = keyof typeof PROVIDERS;
