// AI 服务商配置表
export const PROVIDERS = {
  deepseek: {
    label: 'DeepSeek',
    emoji: '🔵',
    baseUrl: 'https://api.deepseek.com/v1',
    model: 'deepseek-chat',
    keyHint: 'sk-xxxxxxxxxxxxxxxx',
    keyUrl: 'https://platform.deepseek.com/api_keys',
    topUpUrl: 'https://platform.deepseek.com/top_up',
    officialSite: 'https://platform.deepseek.com',
    guideDesc: '适合国内用户，充值门槛低，中文场景表现较好',
    recommendLevel: '推荐',
    difficulty: '低',
    pricingNote: '按官方平台实际价格为准',
    supportsBalance: true,
    supportsVision: false,
  },
  openai: {
    label: 'OpenAI',
    emoji: '🟢',
    baseUrl: 'https://api.openai.com/v1',
    model: 'gpt-4o-mini',
    keyHint: 'sk-xxxxxxxxxxxxxxxx',
    keyUrl: 'https://platform.openai.com/api-keys',
    topUpUrl: 'https://platform.openai.com/settings/organization/billing',
    officialSite: 'https://platform.openai.com',
    guideDesc: '模型生态完整，适合需要通用能力和英文场景的用户',
    recommendLevel: '进阶',
    difficulty: '中',
    pricingNote: '按 OpenAI 官方账单和模型价格为准',
    supportsBalance: false,
    supportsVision: true,
  },
  claude: {
    label: 'Claude（Anthropic）',
    emoji: '🟠',
    baseUrl: 'https://api.anthropic.com',
    model: 'claude-haiku-4-5-20251001',
    keyHint: 'sk-ant-xxxxxxxxxxxxxxxx',
    keyUrl: 'https://platform.claude.com/settings/keys',
    topUpUrl: 'https://platform.claude.com/settings/billing',
    officialSite: 'https://platform.claude.com',
    guideDesc: '适合长文本分析、写作和稳健对话场景',
    recommendLevel: '进阶',
    difficulty: '中',
    pricingNote: '按 Anthropic 官方账单和模型价格为准',
    supportsBalance: false,
    supportsVision: true,
  },
  kimi: {
    label: 'Kimi（月之暗面）',
    emoji: '🌙',
    baseUrl: 'https://api.moonshot.cn/v1',
    model: 'moonshot-v1-8k',
    keyHint: 'sk-xxxxxxxxxxxxxxxx',
    keyUrl: 'https://platform.kimi.com/console/api-keys',
    // 未找到独立可直达的充值页，暂用官方账户页。
    topUpUrl: 'https://platform.kimi.com/console/account',
    officialSite: 'https://platform.kimi.com',
    guideDesc: '适合中文长文本和国内使用场景，平台入口相对清晰',
    recommendLevel: '可选',
    difficulty: '低',
    pricingNote: '按月之暗面官方平台实际价格为准',
    supportsBalance: false,
    supportsVision: false,
  },
  doubao: {
    label: '豆包（火山方舟）',
    emoji: '🌋',
    baseUrl: 'https://ark.cn-beijing.volces.com/api/v3',
    model: 'doubao-seed-1-6-vision-250815',
    keyHint: 'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx',
    keyUrl: 'https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey',
    topUpUrl: 'https://console.volcengine.com/finance/fund',
    officialSite: 'https://www.volcengine.com/product/ark',
    guideDesc: '适合国内中文场景，支持岗位截图和 Offer 图片识别',
    recommendLevel: '推荐',
    difficulty: '低',
    pricingNote: '按火山方舟官方实际价格为准',
    supportsBalance: false,
    supportsVision: true,
  },
  qwen: {
    label: '通义千问',
    emoji: '☁️',
    baseUrl: 'https://dashscope.aliyuncs.com/compatible-mode/v1',
    model: 'qwen-vl-max',
    keyHint: 'sk-xxxxxxxxxxxxxxxx',
    keyUrl: 'https://bailian.console.aliyun.com/?apiKey=1#/api-key',
    topUpUrl: 'https://bailian.console.aliyun.com/#/efm/model_service',
    officialSite: 'https://bailian.console.aliyun.com',
    guideDesc: '阿里云百炼多模态模型，适合中文文本与截图信息提取',
    recommendLevel: '推荐',
    difficulty: '低',
    pricingNote: '按阿里云百炼官方实际价格为准',
    supportsBalance: false,
    supportsVision: true,
  },
  minimax: {
    label: 'MiniMax',
    emoji: '✨',
    baseUrl: 'https://api.minimax.io/v1',
    model: 'MiniMax-M2.5',
    keyHint: 'xxxxxxxxxxxxxxxx',
    keyUrl: 'https://platform.minimaxi.com/user-center/basic-information/interface-key',
    topUpUrl: 'https://platform.minimaxi.com/user-center/payment/balance',
    officialSite: 'https://platform.minimaxi.com',
    guideDesc: '适合中文写作、分析和通用对话，当前用于文字内容识别',
    recommendLevel: '可选',
    difficulty: '低',
    pricingNote: '按 MiniMax 开放平台官方实际价格为准',
    supportsBalance: false,
    supportsVision: false,
  },
  gemini: {
    label: 'Google Gemini',
    emoji: '✦',
    baseUrl: 'https://generativelanguage.googleapis.com/v1beta/openai',
    model: 'gemini-2.5-flash',
    keyHint: 'AIzaSyxxxxxxxxxxxxxxxx',
    keyUrl: 'https://aistudio.google.com/apikey',
    topUpUrl: 'https://console.cloud.google.com/billing',
    officialSite: 'https://aistudio.google.com',
    guideDesc: 'Google 多模态模型，支持长文本、岗位截图和 Offer 图片识别',
    recommendLevel: '推荐',
    difficulty: '低',
    pricingNote: '按 Google AI Studio 官方实际价格为准',
    supportsBalance: false,
    supportsVision: true,
  },
} as const;

export type ProviderId = keyof typeof PROVIDERS;
