import { useState } from 'react';
import { ArrowLeft, MessageCircle, Plus, Send, X, ThumbsUp, Star, Search, Trash2 } from 'lucide-react';

const CATEGORIES=['全部','Offer 分享','面经交流','求职求助','公司评价','岛上闲聊'] as const;
type Reply={id:string;text:string;date:string;author?:string;parentId?:string;replyTo?:string;liked?:boolean;rating?:number};
type Post={id:string;category:string;title:string;body:string;author:string;date:string;example?:boolean;liked?:boolean;replies:Reply[]};
const KEY='sugar-island-board:v1';
const examples:Post[]=[
  {id:'example-offer',category:'Offer 分享',title:'今天，你离理想的工作又近了一点吗？',body:'这是 Offer 分享区的示例帖子。可以聊聊目标岗位、选择 Offer 的考虑，也可以分享自己的好消息。示例内容不代表真实录用信息。',author:'小岛向导',date:'示例内容',example:true,replies:[]},
  {id:'example-interview',category:'面经交流',title:'第一次参加终面，该如何准备？',body:'欢迎分享你的准备方法：项目复盘、自我介绍、反问环节，还有让自己不紧张的小技巧。请避免公开个人联系方式和保密面试题。',author:'小岛向导',date:'示例内容',example:true,replies:[]},
  {id:'example-help',category:'求职求助',title:'想找一起练习面试的同路人',body:'你可以在这里说明专业方向、希望练习的岗位和时间。现在是本机预览版，发布和回复保存在当前浏览器。',author:'小岛向导',date:'示例内容',example:true,replies:[]},
];
function loadPosts():{posts:Post[];warning:string}{
  try{const raw=localStorage.getItem(KEY);if(!raw)return{posts:examples,warning:''};const parsed=JSON.parse(raw);if(!Array.isArray(parsed))throw Error('format');
    return {posts:parsed.filter((p:Post)=>p&&typeof p.id==='string'&&typeof p.title==='string'&&typeof p.body==='string'&&Array.isArray(p.replies)).slice(0,100).map((p:Post)=>({...p,title:p.title.slice(0,80),body:p.body.slice(0,2000),author:typeof p.author==='string'?p.author.slice(0,30):'邻居',date:typeof p.date==='string'?p.date.slice(0,60):'',category:CATEGORIES.includes(p.category as typeof CATEGORIES[number])?p.category:'岛上闲聊',replies:p.replies.filter(r=>r&&typeof r.text==='string'&&typeof r.id==='string').slice(0,50).map(r=>({...r,text:r.text.slice(0,600),author:typeof r.author==='string'?r.author.slice(0,30):'你',parentId:typeof r.parentId==='string'?r.parentId:undefined,replyTo:typeof r.replyTo==='string'?r.replyTo.slice(0,30):undefined,rating:Number.isInteger(r.rating)&&r.rating!>=1&&r.rating!<=5?r.rating:undefined,liked:r.liked===true}))})),warning:''};
  }catch{return{posts:examples,warning:'公告栏存档无法读取，已载入示例帖子。'};}
}
export default function WorldBoard({onClose}:{onClose:()=>void}){
  const [initial]=useState(loadPosts),[posts,setPosts]=useState(initial.posts),[filter,setFilter]=useState('全部');
  const [selected,setSelected]=useState<string|null>(null),[compose,setCompose]=useState(false),[title,setTitle]=useState(''),[body,setBody]=useState(''),[category,setCategory]=useState('求职求助'),[reply,setReply]=useState(''),[notice,setNotice]=useState(initial.warning);
  const [sort,setSort]=useState('最新'),[query,setQuery]=useState(''),[replyTarget,setReplyTarget]=useState<Reply|null>(null),[rating,setRating]=useState(0),[commentsSort,setCommentsSort]=useState('最新');
  const post=posts.find(p=>p.id===selected);
  const persist=(next:Post[])=>{try{localStorage.setItem(KEY,JSON.stringify(next));setPosts(next);return true;}catch{setNotice('浏览器存储失败，内容已保留在输入框，请稍后重试。');return false;}};
  const publish=()=>{
    if(!title.trim()||!body.trim()){setNotice('请填写标题和帖子内容。');return;}
    if(posts.length>=100){setNotice('本机预览最多保留 100 篇帖子。');return;}
    const p:Post={id:crypto.randomUUID(),title:title.trim(),body:body.trim(),category,author:'你',date:new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date()),replies:[]};
    if(persist([p,...posts])){setCompose(false);setSelected(p.id);setTitle('');setBody('');setNotice('帖子已保存到本机预览。');}
  };
  const respond=()=>{if(!post||!reply.trim())return;if(post.replies.length>=50){setNotice('本机预览每篇最多保留 50 条回复。');return;}const r:Reply={id:crypto.randomUUID(),text:reply.trim(),date:new Date().toLocaleString('zh-CN'),author:'你',parentId:replyTarget?(replyTarget.parentId||replyTarget.id):undefined,replyTo:replyTarget?.author||undefined,rating:rating||undefined};if(persist(posts.map(p=>p.id===post.id?{...p,replies:[...p.replies,r]}:p))){setReply('');setReplyTarget(null);setRating(0);setNotice('评论已保存到本机。');requestAnimationFrame(()=>document.querySelector('.comments-heading')?.scrollIntoView({block:'start'}));}};
  const likePost=()=>{if(post)persist(posts.map(p=>p.id===post.id?{...p,liked:!p.liked}:p));};
  const likeReply=(id:string)=>{if(post)persist(posts.map(p=>p.id===post.id?{...p,replies:p.replies.map(r=>r.id===id?{...r,liked:!r.liked}:r)}:p));};
  const deleteReply=(id:string)=>{if(post)persist(posts.map(p=>p.id===post.id?{...p,replies:p.replies.filter(r=>r.id!==id&&r.parentId!==id)}:p));};
  const selectReply=(r:Reply)=>{setReplyTarget(r);setTimeout(()=>document.querySelector<HTMLTextAreaElement>('.forum-reply-form textarea')?.focus(),0);};
  const comment=(r:Reply,nested=false)=><article className={`forum-reply ${nested?'nested':''}`} key={r.id}><header><span className="comment-avatar">{(r.author||'你').slice(0,1)}</span><div><strong>{r.author||'你'}</strong><small>{r.date}</small></div>{r.rating&&<span className="comment-rating">{'★'.repeat(r.rating)}{'☆'.repeat(5-r.rating)}</span>}</header><p>{r.replyTo&&<span className="comment-to">回复 {r.replyTo}：</span>}{r.text}</p><div className="comment-actions"><button aria-label={`点赞评论 ${r.id}`} aria-pressed={!!r.liked} onClick={()=>likeReply(r.id)}><ThumbsUp size={12}/>{r.liked?1:0}</button><button onClick={()=>selectReply(r)}>回复</button>{(!r.author||r.author==='你')&&<button aria-label={`删除评论 ${r.id}`} onClick={()=>deleteReply(r.id)}><Trash2 size={12}/>删除</button>}</div></article>;
  const visiblePosts=posts.filter(p=>(filter==='全部'||p.category===filter)&&(!query||`${p.title} ${p.body}`.includes(query))).sort((a,b)=>sort==='热门'?(b.replies.length+Number(!!b.liked))-(a.replies.length+Number(!!a.liked)):0);
  const roots=post?.replies.filter(r=>!r.parentId||!post.replies.some(p=>p.id===r.parentId))||[];
  const sortedRoots=[...roots].sort((a,b)=>commentsSort==='热门'?Number(!!b.liked)-Number(!!a.liked):post!.replies.indexOf(b)-post!.replies.indexOf(a));
  const ratings=post?.replies.filter(r=>r.rating)||[];
  return <aside className="world-forum" aria-label="世界公告栏"><header><div><span>ISLAND COMMUNITY</span><h2>世界公告栏</h2></div><button className="world-close" aria-label="关闭公告栏" onClick={onClose}><X size={19}/></button></header><p className="forum-preview-note">本机预览 · 帖子与回复尚未向其他用户发布</p>
    {!compose&&!post&&<><div className="forum-filter">{CATEGORIES.map(c=><button key={c} className={filter===c?'active':''} onClick={()=>setFilter(c)}>{c}</button>)}</div><div className="forum-toolbar"><label><Search size={13}/><input aria-label="搜索帖子" placeholder="搜索话题、面经、公司…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="帖子排序" value={sort} onChange={e=>setSort(e.target.value)}><option>最新</option><option>热门</option></select></div><div className="forum-feed">{visiblePosts.map(p=><button key={p.id} className="forum-post-card" onClick={()=>{setSelected(p.id);setNotice('');setReplyTarget(null);setRating(0);}}><span className="forum-category">{p.category}{p.example?' · 示例':''}</span><strong>{p.title}</strong><p>{p.body}</p><small>{p.author} · {p.date}<span><MessageCircle size={12}/>{p.replies.length}</span></small></button>)}{!visiblePosts.length&&<p className="forum-no-posts">这里还没有帖子。来开启第一个话题吧。</p>}</div><footer><button className="world-primary" onClick={()=>{setCompose(true);setNotice('');}}><Plus size={16}/>发布帖子</button></footer></>}
    {compose&&<><div className="forum-body"><button className="forum-back" onClick={()=>setCompose(false)}><ArrowLeft size={14}/>返回帖子列表</button><label className="editor-field">话题分类<select value={category} onChange={e=>setCategory(e.target.value)}>{CATEGORIES.filter(c=>c!=='全部').map(c=><option key={c}>{c}</option>)}</select></label><label className="editor-field">帖子标题<input maxLength={80} value={title} onChange={e=>setTitle(e.target.value)} placeholder="想问什么，或分享什么好消息？"/></label><label className="editor-field">帖子内容<textarea rows={8} maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} placeholder="把问题说具体一点，更容易遇见能帮助你的人。"/></label><small>{body.length}/2000</small></div><footer><button className="world-primary" onClick={publish}><Send size={15}/>确认发布</button></footer></>}
    {post&&!compose&&<><div className="forum-body"><button className="forum-back" onClick={()=>{setSelected(null);setReply('');setNotice('');setReplyTarget(null);setRating(0);}}><ArrowLeft size={14}/>返回帖子列表</button><span className="forum-category">{post.category}{post.example?' · 示例':''}</span><h3>{post.title}</h3><small>{post.author} · {post.date}</small><p className="forum-post-text">{post.body}</p><div className="post-feedback"><button aria-pressed={!!post.liked} onClick={likePost}><ThumbsUp size={15}/>{post.liked?'已赞同 · 1':'赞同这条信息'}</button>{ratings.length>0&&<span><Star size={13}/>{(ratings.reduce((sum,r)=>sum+(r.rating||0),0)/ratings.length).toFixed(1)} / 5 · {ratings.length} 条本机评价</span>}</div><div className="comments-heading"><h4>评论 · {post.replies.length}</h4><select aria-label="评论排序" value={commentsSort} onChange={e=>setCommentsSort(e.target.value)}><option>最新</option><option>热门</option></select></div>{sortedRoots.map(r=><div className="comment-thread" key={r.id}>{comment(r)}{post.replies.filter(c=>c.parentId===r.id).map(c=>comment(c,true))}</div>)}{!post.replies.length&&<p className="forum-no-posts">写下你的第一条回复。</p>}</div><footer className="forum-comment-composer">{replyTarget&&<div className="reply-target">回复 {replyTarget.author||'你'}：{replyTarget.text.slice(0,26)}<button aria-label="取消定向回复" onClick={()=>setReplyTarget(null)}><X size={12}/></button></div>}<div className="comment-rating-picker"><span>评价这条信息</span>{[1,2,3,4,5].map(n=><button key={n} aria-label={`评分 ${n} 星`} aria-pressed={rating===n} onClick={()=>setRating(rating===n?0:n)}><Star size={15} fill={n<=rating?'#bf9d50':'none'}/></button>)}<small>选填</small></div><div className="forum-reply-form"><textarea aria-label="回复内容" maxLength={600} placeholder="分享你的经验或建议…" value={reply} onChange={e=>setReply(e.target.value)}/><button aria-label="发送回复" className="world-primary" onClick={respond} disabled={!reply.trim()}><Send size={16}/></button></div></footer></>}
    {notice&&<div className="forum-notice" role="status">{notice}</div>}
  </aside>;
}
