import { useRef, useState } from 'react';
import { normalizeImportedJson, sectionCompleteness } from '../../lib/resumeAssistantProfile';
import { PROFILE_SECTIONS, type ResumeProfile, type ResumeProfileSection } from '../../types/resumeAssistant';
import { creamCard, ghostBtn, muted, primaryBtn } from './styles';
export function ProfileEditor({ profile, setProfile, onSave, saving, localOnly }: { profile: ResumeProfile; setProfile: (next: ResumeProfile) => void; onSave: () => void; saving: boolean; localOnly: boolean }) {
  const [section, setSection] = useState<ResumeProfileSection>(PROFILE_SECTIONS[0].key);
  const input = useRef<HTMLInputElement>(null);
  const value = profile[section];
  const change = (text: string) => { try { setProfile({ ...profile, [section]: JSON.parse(text) }); } catch { /* retain editing text until valid */ } };
  const importJson = (file?: File) => { if (!file) return; const reader = new FileReader(); reader.onload = () => { try { setProfile(normalizeImportedJson(JSON.parse(String(reader.result)))); } catch { window.alert('导入失败：请选择有效的 JSON 文件。'); } }; reader.readAsText(file); };
  return <section style={creamCard}><div style={{ display: 'flex', justifyContent: 'space-between', gap: 10, flexWrap: 'wrap' }}><div><h2 style={{ margin: 0, fontSize: 18 }}>标准资料</h2><p style={muted}>云端保存前会自动剥离身份证号、护照号和详细地址等敏感字段。</p></div><div style={{ display: 'flex', gap: 8 }}><input ref={input} type="file" accept="application/json" hidden onChange={e => importJson(e.target.files?.[0])}/><button style={ghostBtn} onClick={() => input.current?.click()}>导入 JSON</button><button style={primaryBtn} disabled={saving} onClick={onSave}>{saving ? '保存中…' : localOnly ? '保存本机草稿' : '保存并同步'}</button></div></div><div style={{ display: 'flex', gap: 7, flexWrap: 'wrap', margin: '16px 0' }}>{PROFILE_SECTIONS.map(item => <button key={item.key} onClick={() => setSection(item.key)} style={{ ...ghostBtn, padding: '6px 9px', background: section === item.key ? '#eee4d3' : '#fffdf8' }}>{item.label} {sectionCompleteness(profile, item.key)}%</button>)}</div><textarea aria-label={`${PROFILE_SECTIONS.find(item => item.key === section)?.label} JSON`} value={JSON.stringify(value, null, 2)} onChange={e => change(e.target.value)} spellCheck={false} style={{ width: '100%', minHeight: 250, resize: 'vertical', border: '1px solid #ded4c4', borderRadius: 12, padding: 12, color: '#39342d', background: '#fcfaf5', fontFamily: 'ui-monospace, SFMono-Regular, Menlo, monospace', fontSize: 12, lineHeight: 1.55 }} /><p style={muted}>数组 section 请使用 JSON 数组；普通 section 请使用 JSON 对象。</p></section>;
}
