import { useEffect, useMemo, useState } from 'react';
import type { Interview, InterviewReview, InterviewReviewQuestion, InterviewReviewResult, InterviewRound, NewInterviewReview, QuestionType } from '../types';
import { useCollection } from '../hooks/useCollection';
import { useAppShell } from '../contexts/AppShellContext';
import { useTheme } from '../contexts/ThemeContext';
import Modal from '../components/Modal';
import { Field, FormError, GhostButton, PrimaryButton, Select, TextArea, TextInput } from '../components/Field';
import EmptyState from '../components/EmptyState';
import { CARD } from '../lib/appHelpers';

const rounds: InterviewRound[] = ['一面','二面','技术面','主管面','HR面'];
const results: InterviewReviewResult[] = ['通过','未通过','待通知','主动放弃'];
const questionTypes: QuestionType[] = ['自我介绍','项目经历','实习经历','专业问题','行为面试','HR问题','反问','其他'];
const blank: NewInterviewReview = { application_id:null,interview_id:null,company_name:'',position_name:'',round:'一面',interviewer_role:'',
  interview_time:null,interview_form:'视频',result:'待通知',reviewed:false,mistake_tags:[],performance_score:null,
  clarity_score:null,matching_score:null,storytelling_score:null,logic_score:null,confidence_score:null,question_quality_score:null,
  star_s:'',star_t:'',star_a:'',star_r:'',star_resume_ref:'',good_points:'',weak_points:'',improve_knowledge:'',
  improve_answers:'',improve_prep:'',improvement_plan:'',next_action:'',next_action_at:null,notes:'' };
type DraftQ = Pick<InterviewReviewQuestion,'question_text'|'question_type'|'my_answer'|'better_answer'|'answer_score'|'problem'|'add_to_question_bank'|'mastery_status'>;
const emptyQ: DraftQ = { question_text:'',question_type:'项目经历',my_answer:'',better_answer:'',answer_score:null,problem:'',add_to_question_bank:false,mastery_status:'需练习' };
const date = (v:string|null) => v ? new Date(v).toLocaleString('zh-CN',{dateStyle:'medium',timeStyle:'short'}) : '—';

export default function InterviewReviews() {
  const reviews = useCollection<InterviewReview>('interview_reviews',{column:'interview_time',ascending:false});
  const questions = useCollection<InterviewReviewQuestion>('interview_review_questions');
  const interviews = useCollection<Interview>('interviews',{column:'interview_time',ascending:false});
  const { query, registerAdd } = useAppShell(); const { theme } = useTheme();
  const [view,setView] = useState<'list'|'bank'>('list'); const [round,setRound] = useState('全部轮次');
  const [result,setResult] = useState('全部结果'); const [form,setForm] = useState<NewInterviewReview>(blank);
  const [draftQs,setDraftQs] = useState<DraftQ[]>([{...emptyQ}]); const [editing,setEditing] = useState<InterviewReview|null>(null);
  const [detail,setDetail] = useState<InterviewReview|null>(null); const [modal,setModal] = useState(false);
  const [step,setStep] = useState(0); const [formError,setFormError] = useState(''); const [saving,setSaving] = useState(false);
  const openCreate = () => { setEditing(null);setForm(blank);setDraftQs([{...emptyQ}]);setStep(0);setFormError('');setModal(true); };
  useEffect(()=>{registerAdd(openCreate);return()=>registerAdd(null)},[registerAdd]);
  const patch = <K extends keyof NewInterviewReview>(k:K,v:NewInterviewReview[K])=>setForm(x=>({...x,[k]:v}));
  const selectInterview=(id:string)=>{const x=interviews.items.find(i=>i.id===id);setForm(v=>({...v,interview_id:id||null,company_name:x?.company_name??v.company_name,position_name:x?.position_name??v.position_name,interview_time:x?.interview_time??v.interview_time,round:(x?.round as InterviewRound)??v.round,interview_form:x?.interview_type??v.interview_form}))};
  const openEdit=(r:InterviewReview)=>{setEditing(r);setForm({...r});const qs=questions.items.filter(q=>q.review_id===r.id).map(q=>({...q}));setDraftQs(qs.length?qs:[{...emptyQ}]);setStep(0);setModal(true)};
  const save=async()=>{if(!form.company_name.trim())return setFormError('公司名称为必填项。');setSaving(true);setFormError('');
    const scores=[form.clarity_score,form.matching_score,form.storytelling_score,form.logic_score,form.confidence_score,form.question_quality_score].filter(x=>x!=null) as number[];
    const payload={...form,reviewed:true,performance_score:scores.length?Math.round(scores.reduce((a,b)=>a+b,0)/scores.length):form.performance_score};
    try { const saved=editing?await reviews.update(editing.id,payload):await reviews.create(payload);
      if(editing){for(const q of questions.items.filter(x=>x.review_id===editing.id))await questions.remove(q.id)}
      for(const q of draftQs.filter(x=>x.question_text.trim())) await questions.create({...q,review_id:saved.id,issue_tags:[],star_situation:null,star_task:null,star_action:null,star_result:null});
      setModal(false);
    }catch(e){setFormError(e instanceof Error?e.message:String(e))}finally{setSaving(false)}};
  const del=async(r:InterviewReview)=>{if(confirm(`确定删除「${r.company_name}」的复盘吗？`))await reviews.remove(r.id)};
  const list=useMemo(()=>reviews.items.filter(x=>round==='全部轮次'||x.round===round).filter(x=>result==='全部结果'||x.result===result).filter(x=>!query||[x.company_name,x.position_name,...questions.items.filter(q=>q.review_id===x.id).map(q=>q.question_text)].some(v=>v?.toLowerCase().includes(query.toLowerCase()))),[reviews.items,questions.items,round,result,query]);
  const bank=questions.items.filter(x=>x.add_to_question_bank);
  const stats=[['已复盘',reviews.items.filter(x=>x.reviewed).length,'完成记录'],['待复盘',reviews.items.filter(x=>!x.reviewed).length,'需要处理'],['通过',reviews.items.filter(x=>x.result==='通过').length,'面试通过'],['未通过',reviews.items.filter(x=>x.result==='未通过').length,'继续改进'],['平均表现',reviews.items.length?Math.round(reviews.items.reduce((a,b)=>a+(b.performance_score??0),0)/reviews.items.length):0,'综合评分'],['题库题数',bank.length,'持续积累']];
  const detailQs=detail?questions.items.filter(x=>x.review_id===detail.id):[];
  return <div className="flex flex-col gap-[18px] animate-rise">
    {(reviews.error||questions.error)&&<FormError message={reviews.error||questions.error||''}/>}
    <div className="grid grid-cols-2 xl:grid-cols-6 gap-3">{stats.map(([a,b,c],i)=><div key={String(a)} style={{...CARD,padding:16,background:['#dcebd5','#fbeec2','#dde8fb','#fbe0d8',theme.accentSoft,'#e6e2da'][i]}}><div className="text-xs font-semibold opacity-70">{a}</div><div className="text-2xl font-bold mt-1">{b}</div><div className="text-[11px] opacity-60">{c}</div></div>)}</div>
    <div className="grid grid-cols-2 sm:flex gap-3 p-3" style={{...CARD,borderRadius:18}}>
      <div className="flex rounded-xl bg-[#f5f0e7] p-1"><button style={tab(view==='list')} onClick={()=>setView('list')}>复盘列表</button><button style={tab(view==='bank')} onClick={()=>setView('bank')}>面试题库</button></div>
      {view==='list'&&<><Select value={round} onChange={e=>setRound(e.target.value)}><option>全部轮次</option>{rounds.map(x=><option key={x}>{x}</option>)}</Select><Select value={result} onChange={e=>setResult(e.target.value)}><option>全部结果</option>{results.map(x=><option key={x}>{x}</option>)}</Select></>}
      <PrimaryButton accent={theme.accent} onClick={openCreate}>＋ 新增复盘</PrimaryButton>
    </div>
    {reviews.loading?<EmptyState text="正在加载面试复盘…"/>:view==='bank'?bank.length?<div className="grid gap-3">{bank.map(q=>{const owner=reviews.items.find(x=>x.id===q.review_id);return <article key={q.id} style={{...CARD,padding:20}}><div className="flex justify-between gap-3"><div><span style={typePill}>{q.question_type}</span><h3 className="mt-3 mb-1">{q.question_text}</h3><p className="text-xs text-[#8a8478]">来源：{owner?.company_name} · {owner?.position_name}</p></div><button style={tab(true)} onClick={()=>void questions.update(q.id,{mastery_status:q.mastery_status==='已掌握'?'需练习':'已掌握'})}>{q.mastery_status}</button></div><div className="mt-3 bg-[#faf7f0] rounded-xl p-3 text-sm"><b>优化回答</b><p>{q.better_answer||'尚未整理'}</p></div></article>})}</div>:<EmptyState text="题库还是空的。在复盘问题中勾选“加入题库”即可积累。"/>:
      list.length?<div className="grid grid-cols-1 xl:grid-cols-2 gap-4">{list.map(r=><article key={r.id} className="card-hover" style={{...CARD,padding:20}}><div className="flex justify-between gap-3"><div><h3 className="m-0">{r.company_name}</h3><p className="text-sm text-[#8a8478] mt-1">{r.position_name||'岗位未填'} · {r.round} · {r.interview_form}</p></div><span style={resultPill(r.result)}>{r.result}</span></div><div className="grid grid-cols-3 gap-3 my-4 text-sm"><div><small>面试时间</small><b className="block">{date(r.interview_time)}</b></div><div><small>复盘状态</small><b className="block">{r.reviewed?'已复盘':'待复盘'}</b></div><div><small>表现评分</small><b className="block">{r.performance_score??'—'} 分</b></div></div><div className="flex flex-wrap gap-2 mb-3">{(r.mistake_tags??[]).map(x=><span className="text-xs bg-[#fbe0d8] rounded-full px-2 py-1" key={x}>{x}</span>)}</div><div className="flex justify-end gap-2 border-t pt-3"><GhostButton onClick={()=>setDetail(r)}>查看详情</GhostButton><GhostButton onClick={()=>openEdit(r)}>编辑</GhostButton><GhostButton onClick={()=>void del(r)}>删除</GhostButton></div></article>)}</div>:
      <EmptyState text="还没有面试复盘。面试结束后记录问题和表现，下一次准备会更快。" actionLabel="新增复盘" onAction={openCreate}/>}
    {detail&&<div className="fixed inset-0 z-[90] bg-black/25" onClick={()=>setDetail(null)}><aside className="absolute right-0 h-full w-full sm:w-[560px] overflow-y-auto bg-[#fffdf8] p-6" onClick={e=>e.stopPropagation()}><div className="flex justify-between"><h2>{detail.company_name} · {detail.round}</h2><button className="w-11 h-11 rounded-xl border" onClick={()=>setDetail(null)}>×</button></div><Detail title="基本信息">{detail.position_name} · {detail.interview_form} · {date(detail.interview_time)}</Detail><Detail title="面试问题">{detailQs.map(q=><div className="mb-4" key={q.id}><b>{q.question_text}</b><p>我的回答：{q.my_answer||'—'}</p><p>优化回答：{q.better_answer||'—'}</p><span>{q.answer_score??'—'} 分 · {q.question_type}</span></div>)}</Detail><Detail title="STAR 复盘">S：{detail.star_s||'—'}<br/>T：{detail.star_t||'—'}<br/>A：{detail.star_a||'—'}<br/>R：{detail.star_r||'—'}</Detail><Detail title="优点与失误">{detail.good_points||'—'}<br/>{detail.weak_points||'—'}</Detail><Detail title="下次改进">{detail.improvement_plan||detail.improve_prep||'—'}</Detail><PrimaryButton accent={theme.accent} onClick={()=>{setDetail(null);setView('bank')}}>进入面试题库</PrimaryButton></aside></div>}
    <Modal open={modal} title={editing?'编辑面试复盘':'新增面试复盘'} onClose={()=>setModal(false)} footer={<><GhostButton disabled={step===0} onClick={()=>setStep(s=>s-1)}>上一步</GhostButton><GhostButton onClick={()=>setModal(false)}>取消</GhostButton><PrimaryButton accent={theme.accent} onClick={()=>step<3?setStep(s=>s+1):void save()} disabled={saving}>{step<3?'下一步 →':saving?'保存中…':'完成复盘'}</PrimaryButton></>}>
      <div className="grid grid-cols-4 gap-1 mb-5">{['基本信息','面试问题','整体复盘','下次改进'].map((x,i)=><div key={x} className="text-center text-xs font-bold rounded-lg p-2" style={{background:i===step?theme.accent:i<step?theme.accentSoft:'#f5f0e7',color:i===step?'white':'#6b665c'}}>{x}</div>)}</div><FormError message={formError}/>
      {step===0&&<><Field label="选择已有面试"><Select value={form.interview_id??''} onChange={e=>selectInterview(e.target.value)}><option value="">手动录入</option>{interviews.items.map(x=><option key={x.id} value={x.id}>{x.company_name} · {x.round} · {date(x.interview_time)}</option>)}</Select></Field><div className="grid sm:grid-cols-2 gap-x-3"><Field label="公司名称 *"><TextInput value={form.company_name} onChange={e=>patch('company_name',e.target.value)}/></Field><Field label="岗位名称"><TextInput value={form.position_name??''} onChange={e=>patch('position_name',e.target.value)}/></Field><Field label="面试轮次"><Select value={form.round??''} onChange={e=>patch('round',e.target.value as InterviewRound)}>{rounds.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="面试结果"><Select value={form.result} onChange={e=>patch('result',e.target.value as InterviewReviewResult)}>{results.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="面试形式"><Select value={form.interview_form??''} onChange={e=>patch('interview_form',e.target.value as '电话'|'视频'|'现场')}><option>电话</option><option>视频</option><option>现场</option></Select></Field><Field label="面试时间"><TextInput type="datetime-local" value={form.interview_time?.slice(0,16)??''} onChange={e=>patch('interview_time',e.target.value||null)}/></Field></div></>}
      {step===1&&<>{draftQs.map((q,i)=><div key={i} className="bg-[#faf7f0] rounded-2xl p-4 mb-3"><div className="flex justify-between"><b>问题 {i+1}</b>{draftQs.length>1&&<button onClick={()=>setDraftQs(v=>v.filter((_,j)=>j!==i))}>移除</button>}</div><Field label="问题"><TextArea value={q.question_text} onChange={e=>setDraftQs(v=>v.map((x,j)=>j===i?{...x,question_text:e.target.value}:x))}/></Field><Field label="问题类型"><Select value={q.question_type??''} onChange={e=>setDraftQs(v=>v.map((x,j)=>j===i?{...x,question_type:e.target.value as QuestionType}:x))}>{questionTypes.map(x=><option key={x}>{x}</option>)}</Select></Field><Field label="我的回答"><TextArea value={q.my_answer??''} onChange={e=>setDraftQs(v=>v.map((x,j)=>j===i?{...x,my_answer:e.target.value}:x))}/></Field><Field label="优化回答"><TextArea value={q.better_answer??''} onChange={e=>setDraftQs(v=>v.map((x,j)=>j===i?{...x,better_answer:e.target.value}:x))}/></Field><label><input type="checkbox" checked={q.add_to_question_bank} onChange={e=>setDraftQs(v=>v.map((x,j)=>j===i?{...x,add_to_question_bank:e.target.checked}:x))}/> 加入面试题库</label></div>)}<GhostButton onClick={()=>setDraftQs(v=>[...v,{...emptyQ}])}>＋ 添加问题</GhostButton></>}
      {step===2&&<><div className="grid grid-cols-2 gap-x-3">{(['clarity_score','matching_score','storytelling_score','logic_score','confidence_score','question_quality_score'] as const).map((k,i)=><Field key={k} label={['表达清晰度','专业匹配度','项目讲述','逻辑结构','自信程度','反问质量'][i]}><TextInput type="number" min="0" max="100" value={form[k]??''} onChange={e=>patch(k,e.target.value===''?null:Number(e.target.value))}/></Field>)}</div><Field label="做得好的地方"><TextArea value={form.good_points??''} onChange={e=>patch('good_points',e.target.value)}/></Field><Field label="失误与薄弱点"><TextArea value={form.weak_points??''} onChange={e=>patch('weak_points',e.target.value)}/></Field><div className="grid grid-cols-2 gap-x-3">{(['star_s','star_t','star_a','star_r'] as const).map(k=><Field key={k} label={k.toUpperCase()}><TextArea value={form[k]??''} onChange={e=>patch(k,e.target.value)}/></Field>)}</div></>}
      {step===3&&<><Field label="知识补齐"><TextArea value={form.improve_knowledge??''} onChange={e=>patch('improve_knowledge',e.target.value)}/></Field><Field label="回答优化"><TextArea value={form.improve_answers??''} onChange={e=>patch('improve_answers',e.target.value)}/></Field><Field label="下次面试前准备"><TextArea value={form.improve_prep??''} onChange={e=>patch('improve_prep',e.target.value)}/></Field><Field label="完整改进计划"><TextArea value={form.improvement_plan??''} onChange={e=>patch('improvement_plan',e.target.value)}/></Field></>}
    </Modal>
  </div>
}
function Detail({title,children}:{title:string;children:React.ReactNode}){return <section className="mb-5"><h3>{title}</h3><div className="bg-[#faf7f0] rounded-2xl p-4 text-sm leading-7">{children}</div></section>}
const tab=(a:boolean):React.CSSProperties=>({minHeight:36,padding:'0 14px',border:0,borderRadius:9,background:a?'#fffdf8':'transparent',fontWeight:700});
const typePill:React.CSSProperties={fontSize:12,fontWeight:700,padding:'4px 10px',borderRadius:999,background:'#dde8fb',color:'#345b9a'};
const resultPill=(r:InterviewReviewResult):React.CSSProperties=>({...typePill,background:r==='通过'?'#dcebd5':r==='未通过'?'#fbe0d8':r==='待通知'?'#e4e0f7':'#e6e2da'});
