import { getServiceSupabase, requireDeviceToken, requireUserFromJwt } from './_lib/auth';
import { sha256Hex } from './_lib/crypto';
import { handleOptions, json } from './_lib/cors';
export const config = { runtime: 'edge' };
const sensitive: Array<[string, string]> = [['personal', 'idNumber'], ['personal', 'passportNumber'], ['personal', 'detailedAddress'], ['personal', 'addressLine1'], ['personal', 'addressLine2'], ['personal', 'streetAddress'], ['identity', 'idNumber'], ['identity', 'passportNumber'], ['contact', 'detailedAddress']];
function strip(input: unknown) { const clean = structuredClone(input && typeof input === 'object' ? input : {}) as Record<string, unknown>; for (const [section, field] of sensitive) { const object = clean[section]; if (object && typeof object === 'object' && !Array.isArray(object)) delete (object as Record<string, unknown>)[field]; } return clean; }
export default async function handler(request: Request) { if (request.method === 'OPTIONS') return handleOptions(request); try { const service = getServiceSupabase(); if (request.method === 'GET') { const isDevice = Boolean(request.headers.get('x-device-token') || (request.headers.get('authorization') ?? '').startsWith('Device ')); const device = isDevice ? await requireDeviceToken(request, 'profile:read') : null; const auth = device ? { userId: device.userId, deviceId: device.deviceId } : { userId: (await requireUserFromJwt(request)).id, deviceId: null }; const { data, error } = await service.from('autofill_profiles').select('id,user_id,profile,revision,profile_hash,schema_version,sync_scope,updated_at').eq('user_id', auth.userId).maybeSingle(); if (error) throw error; if (auth.deviceId) await service.from('extension_devices').update({ last_seen_at: new Date().toISOString(), last_sync_revision: data?.revision ?? null }).eq('id', auth.deviceId); return json(request, { profile: data ?? null }); }
    if (request.method === 'PUT' || request.method === 'POST') { const user = await requireUserFromJwt(request); const body = await request.json() as { profile?: unknown; sync_scope?: unknown }; const profile = strip(body.profile); const sync_scope = body.sync_scope && typeof body.sync_scope === 'object' ? body.sync_scope : {}; const { data: previous } = await service.from('autofill_profiles').select('revision').eq('user_id', user.id).maybeSingle(); const row = { user_id: user.id, profile, sync_scope, schema_version: 4, profile_hash: await sha256Hex(JSON.stringify(profile)), revision: (previous?.revision ?? 0) + 1 }; const { data, error } = await service.from('autofill_profiles').upsert(row, { onConflict: 'user_id' }).select('id,user_id,profile,revision,profile_hash,schema_version,sync_scope,updated_at').single(); if (error) throw error; return json(request, { profile: data }); }
    return json(request, { error: 'Method not allowed' }, 405);
  } catch (error) { return json(request, { error: error instanceof Error && /Unauthorized/.test(error.message) ? 'Unauthorized' : 'Profile service unavailable' }, error instanceof Error && /Unauthorized/.test(error.message) ? 401 : 503); } }
