import { getServiceSupabase, requireDeviceToken, requireUserFromJwt } from './_lib/auth';
import { handleOptions, json } from './_lib/cors';
export const config = { runtime: 'edge' };
const validStatus = new Set(['success', 'partial', 'failed', 'cancelled']);
const strings = (value: unknown, max = 20) => Array.isArray(value) ? value.filter(item => typeof item === 'string').slice(0, max).map(item => item.slice(0, 120)) : [];
export default async function handler(request: Request) { if (request.method === 'OPTIONS') return handleOptions(request); try { const service = getServiceSupabase(); if (request.method === 'GET') { const user = await requireUserFromJwt(request); const { data, error } = await service.from('autofill_runs').select('id,origin_host,page_path_hash,status,fields_total,fields_filled,fields_manual,error_codes,adapter_names,created_at').eq('user_id', user.id).order('created_at', { ascending: false }).limit(100); if (error) throw error; return json(request, { runs: data ?? [] }); }
    if (request.method === 'POST') { const device = await requireDeviceToken(request, 'run:write'); const body = await request.json() as Record<string, unknown>; const origin_host = String(body.origin_host ?? '').toLowerCase(); if (!/^[a-z0-9.-]+$/i.test(origin_host) || origin_host.length > 253) return json(request, { error: 'Invalid origin host' }, 400); const status = String(body.status ?? 'partial'); if (!validStatus.has(status)) return json(request, { error: 'Invalid status' }, 400); const num = (name: string) => Math.max(0, Math.min(9999, Number(body[name]) || 0)); const { error } = await service.from('autofill_runs').insert({ user_id: device.userId, device_id: device.deviceId, origin_host, page_path_hash: typeof body.page_path_hash === 'string' ? body.page_path_hash.slice(0, 128) : null, status, fields_total: num('fields_total'), fields_filled: num('fields_filled'), fields_manual: num('fields_manual'), error_codes: strings(body.error_codes), adapter_names: strings(body.adapter_names) }); if (error) throw error; return json(request, { ok: true }, 201); }
    if (request.method === 'DELETE') { const user = await requireUserFromJwt(request); const { id } = await request.json() as { id?: string }; if (!id) return json(request, { error: 'Run id required' }, 400); const { data } = await service.from('autofill_runs').delete().eq('id', id).eq('user_id', user.id).select('id').maybeSingle(); return data ? json(request, { ok: true }) : json(request, { error: 'Run not found' }, 404); }
    return json(request, { error: 'Method not allowed' }, 405);
  } catch (error) { return json(request, { error: error instanceof Error && /Unauthorized/.test(error.message) ? 'Unauthorized' : 'Run service unavailable' }, error instanceof Error && /Unauthorized/.test(error.message) ? 401 : 503); } }
